const surveyedSkills = [
  "classifying",
  "collating",
  "comparing",
  "compiling",
  "composing",
  "computing",
  "coordinating",
  "copying",
  "creating",
  "developing ideas",
  "evaluating",
  "examining",
  "filing",
  "gathering",
  "interpreting",
  "investigating",
  "managing money",
  "observing",
  "organizing",
  "presenting",
  "reading",
  "recording",
  "reporting",
  "researching",
  "sorting",
  "synthesizing",
  "transcribing",
  "writing",
  "advising",
  "caring for",
  "confronting others",
  "consulting",
  "coordinating",
  "counseling",
  "directing",
  "empathizing",
  "entertaining",
  "guiding",
  "helping",
  "influencing others",
  "informing",
  "instructing",
  "interpreting",
  "leading",
  "listening",
  "managing",
  "motivating",
  "negotiating",
  "persuading",
  "serving",
  "speaking",
  "supervising",
  "supporting",
  "taking instructions",
  "teaching",
  "training",
  "treating",
  "handling",
  "loading",
  "manipulating",
  "monitoring",
  "moving",
  "operating",
  "controlling",
  "precision working",
  "preparing",
  "pushing",
  "regulating",
  "remodeling",
  "repairing",
  "setting up",
  "stacking",
  "tending",
  "adjusting",
  "assembling",
  "building",
  "calibrating",
  "carrying",
  "crafting",
  "cutting",
  "demonstrating",
  "designing",
  "disassembling",
  "driving",
  "operating",
  "finishing",
  "refining",
  "acupuncture",
  "framing",
  "appraising",
  "glazing",
  "acting",
  "hairstyling",
  "auto body repair",
  "harvesting",
  "auto engine tune-up",
  "horse breeding",
  "basketball",
  "housekeeping",
  "blueprint reading",
  "hunting",
  "book binding",
  "intelligence gathering",
  "bricklaying",
  "jewelry making",
  "bridge designing",
  "landscaping",
  "building inspection",
  "legal research",
  "cabinet making",
  "line installation",
  "cake decorating",
  "manicuring",
  "carpet installation",
  "meat inspection",
  "chimney cleaning",
  "medicine dispensing",
  "choreography",
  "metalworking skills",
  "color analyzing",
  "mild processing",
  "computer programming",
  "millwright skills",
  "cooking",
  "mine cutting",
  "cost estimation",
  "motion film directing",
  "costume design",
  "navigating",
  "drawing",
  "orthodontic",
  "eeg procedures",
  "pattern making",
  "electric skill",
  "pet-grooming",
  "elevator repair",
  "photography",
  "embalming",
  "plastering",
  "eyeglass fitting",
  "plumbing",
  "equipment repair",
  "fire fighting",
  "first-aid skills",
  "fishing",
  "proofreading",
  "flower arranging",
  "flying",
  "radio announcing",
  "food-packing",
  "poultry cutting",
  "precision assembling",
  "printing operation",
  "radar operation",
  "real estate",
  "reference",
  "roofing",
  "sailing",
  "sculpting",
  "set design",
  "sewing",
  "sharp shotting",
  "sheet-metal",
  "ship fitting",
  "shoe repair",
  "solar heater",
  "spacecraft designing",
  "spinal adjustment",
  "surveying",
  "tax preparation",
  "teeth cleaning",
  "telegraph operation",
  "tile setting",
  "timber cutting",
  "tool making",
  "typesetting",
  "upholstery",
  "musical instruments",
  "warehousing",
  "weaving",
  "welding",
  "window dressing",
  "window washing",
  "writing advertisement",
  "x-ray machine",
];
